- name: Install apache service
  apt:
    name: apache2
    update_cache: yes
    state: latest

- name: Install apache-utils
  apt:
    name: apache2-utils
    update_cache: yes
    state: latest

- name: Start httpd service
  systemd:
    name: apache2
    state: started
    enabled: yes

    #- name: Firewall allow apache
    #community.general.ufw:
    #rule: allow
    #name: Apache
