- name: Download wordpress
  unarchive:
    src: https://wordpress.org/latest.tar.gz
    dest: "/var/www/html/"
    remote_src: yes

- name: Recursively change ownership of a /var/www/html/wordpres dir
  ansible.builtin.file:
    path: /var/www/html/wordpress
    state: directory
    recurse: yes
    owner: apache
    group: apache
    mode: 775

